[2025-02-13T04:16:17.435+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T04:16:17.480+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: workflow_1.upload_data_to_s3 manual__2025-02-13T04:15:58.244810+00:00 [queued]>
[2025-02-13T04:16:17.517+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: workflow_1.upload_data_to_s3 manual__2025-02-13T04:15:58.244810+00:00 [queued]>
[2025-02-13T04:16:17.518+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-13T04:16:17.584+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): upload_data_to_s3> on 2025-02-13 04:15:58.244810+00:00
[2025-02-13T04:16:17.601+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'workflow_1', 'upload_data_to_s3', 'manual__2025-02-13T04:15:58.244810+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/retry.py', '--cfg-path', '/tmp/tmpps289p7m']
[2025-02-13T04:16:17.609+0000] {standard_task_runner.py:105} INFO - Job 25: Subtask upload_data_to_s3
[2025-02-13T04:16:17.615+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=290) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-13T04:16:17.617+0000] {standard_task_runner.py:72} INFO - Started process 300 to run task
[2025-02-13T04:16:17.791+0000] {task_command.py:467} INFO - Running <TaskInstance: workflow_1.upload_data_to_s3 manual__2025-02-13T04:15:58.244810+00:00 [running]> on host f6cd8c636678
[2025-02-13T04:16:17.986+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='workflow_1' AIRFLOW_CTX_TASK_ID='upload_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T04:15:58.244810+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T04:15:58.244810+00:00'
[2025-02-13T04:16:17.988+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-13T04:16:18.033+0000] {base.py:84} INFO - Retrieving connection 's3_conn'
[2025-02-13T04:16:18.034+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-13T04:16:29.388+0000] {hook.py:208} WARNING - Data lineage tracking is disabled. Register a hook lineage reader to start tracking hook lineage.
[2025-02-13T04:16:29.391+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-13T04:16:29.433+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-13T04:16:29.434+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=workflow_1, task_id=upload_data_to_s3, run_id=manual__2025-02-13T04:15:58.244810+00:00, execution_date=20250213T041558, start_date=20250213T041617, end_date=20250213T041629
[2025-02-13T04:16:29.567+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-13T04:16:29.615+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-13T04:16:29.619+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
