[2025-02-13T21:51:05.196+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T21:51:05.224+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: workflow_2.upload_data_to_s3 manual__2025-02-13T21:50:49.762428+00:00 [queued]>
[2025-02-13T21:51:05.243+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: workflow_2.upload_data_to_s3 manual__2025-02-13T21:50:49.762428+00:00 [queued]>
[2025-02-13T21:51:05.244+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-13T21:51:05.276+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): upload_data_to_s3> on 2025-02-13 21:50:49.762428+00:00
[2025-02-13T21:51:05.283+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'workflow_2', 'upload_data_to_s3', 'manual__2025-02-13T21:50:49.762428+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/DAG_2.py', '--cfg-path', '/tmp/tmp2il33ffm']
[2025-02-13T21:51:05.286+0000] {standard_task_runner.py:105} INFO - Job 37: Subtask upload_data_to_s3
[2025-02-13T21:51:05.288+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1439) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-13T21:51:05.288+0000] {standard_task_runner.py:72} INFO - Started process 1449 to run task
[2025-02-13T21:51:05.378+0000] {task_command.py:467} INFO - Running <TaskInstance: workflow_2.upload_data_to_s3 manual__2025-02-13T21:50:49.762428+00:00 [running]> on host f6cd8c636678
[2025-02-13T21:51:05.511+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='workflow_2' AIRFLOW_CTX_TASK_ID='upload_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T21:50:49.762428+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T21:50:49.762428+00:00'
[2025-02-13T21:51:05.512+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-13T21:51:05.542+0000] {base.py:84} INFO - Retrieving connection 's3_conn'
[2025-02-13T21:51:05.543+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-13T21:51:20.698+0000] {hook.py:208} WARNING - Data lineage tracking is disabled. Register a hook lineage reader to start tracking hook lineage.
[2025-02-13T21:51:20.699+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-13T21:51:20.720+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-13T21:51:20.721+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=workflow_2, task_id=upload_data_to_s3, run_id=manual__2025-02-13T21:50:49.762428+00:00, execution_date=20250213T215049, start_date=20250213T215105, end_date=20250213T215120
[2025-02-13T21:51:20.816+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-13T21:51:20.845+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-13T21:51:20.848+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
