[2025-02-13T20:40:57.541+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T20:40:57.573+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: workflow_2.upload_data_to_s3 manual__2025-02-13T20:40:40.121374+00:00 [queued]>
[2025-02-13T20:40:57.591+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: workflow_2.upload_data_to_s3 manual__2025-02-13T20:40:40.121374+00:00 [queued]>
[2025-02-13T20:40:57.592+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-13T20:40:57.630+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): upload_data_to_s3> on 2025-02-13 20:40:40.121374+00:00
[2025-02-13T20:40:57.638+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'workflow_2', 'upload_data_to_s3', 'manual__2025-02-13T20:40:40.121374+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/DAG_2.py', '--cfg-path', '/tmp/tmp_h4w1y52']
[2025-02-13T20:40:57.641+0000] {standard_task_runner.py:105} INFO - Job 34: Subtask upload_data_to_s3
[2025-02-13T20:40:57.643+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1116) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-13T20:40:57.644+0000] {standard_task_runner.py:72} INFO - Started process 1126 to run task
[2025-02-13T20:40:57.737+0000] {task_command.py:467} INFO - Running <TaskInstance: workflow_2.upload_data_to_s3 manual__2025-02-13T20:40:40.121374+00:00 [running]> on host f6cd8c636678
[2025-02-13T20:40:57.868+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='workflow_2' AIRFLOW_CTX_TASK_ID='upload_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T20:40:40.121374+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T20:40:40.121374+00:00'
[2025-02-13T20:40:57.870+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-13T20:40:57.904+0000] {base.py:84} INFO - Retrieving connection 's3_conn'
[2025-02-13T20:40:57.905+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-13T20:41:10.119+0000] {hook.py:208} WARNING - Data lineage tracking is disabled. Register a hook lineage reader to start tracking hook lineage.
[2025-02-13T20:41:10.120+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-13T20:41:10.149+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-13T20:41:10.150+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=workflow_2, task_id=upload_data_to_s3, run_id=manual__2025-02-13T20:40:40.121374+00:00, execution_date=20250213T204040, start_date=20250213T204057, end_date=20250213T204110
[2025-02-13T20:41:10.248+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-13T20:41:10.274+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-13T20:41:10.276+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
